apiVersion: v1
kind: Service
metadata:
  name: daphine
spec:
  selector:
    app: daphine
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: daphine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daphine
    template:
      metadata:
        labels:
          app: daphine
      spec:
        containers:
          - name: daphine
            image: node:latest
            ports:
              - containerPort: 3000
            env:
              - name: PUPPETEER_SKIP_DOWNLOAD
                value: true
              - name: VOLUME_PATH
                value: /juche
            imagePullPolicy: Always